add purpur server docker container, add step to retrieve server logs for all runs

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -32,9 +32,9 @@ jobs:
     # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
     # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
     - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
+      uses: gradle/actions/setup-gradle@v4 # v4.0.0
 
-    - name: Build with Gradle Wrapper
+    - name: Execute Gradle build
       run: ./gradlew build
 
     - name: Upload plugin JAR
@@ -74,17 +74,14 @@ jobs:
   test-paper:
     needs: build
     runs-on: ubuntu-latest
-
     steps:
       - name: Download plugin JAR
         uses: actions/download-artifact@v4
         with:
           name: plugin-jar
           path: plugins
-
       - name: Set up Docker
         uses: docker/setup-buildx-action@v3
-
       - name: Run PaperMC Server in Docker with plugin
         run: |
             docker run -d \
@@ -95,10 +92,8 @@ jobs:
             -v ${{ github.workspace }}/plugins:/plugins \
             -p 25565:25565 \
             itzg/minecraft-server:latest
-            
-            echo "Waiting for server to start..."
+            echo "Starting Paper server..."
             sleep 1
-
       - name: Delayed server health check
         run: |
           echo "Waiting for server to become healthy..."
@@ -111,10 +106,54 @@ jobs:
             fi
             sleep 6
           done
-          echo "Server failed to become healthy in time."
-          docker logs test-paper-server
+          echo "Server failed health check, timeout."
           exit 1
-
+      - name: Retrieve server logs
+        run: docker logs test-paper-server
       - name: Stop and clean up
         if: always()
         run: docker rm -f test-paper-server || true
+
+
+  test-purpur:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download plugin JAR
+        uses: actions/download-artifact@v4
+        with:
+          name: plugin-jar
+          path: plugins
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v3
+      - name: Run PaperMC Server in Docker with plugin
+        run: |
+          docker run -d \
+          --name test-purpur-server \
+          -e EULA=TRUE \
+          -e TYPE=PURPUR \
+          -e VERSION=1.21.1 \
+          -v ${{ github.workspace }}/plugins:/plugins \
+          -p 25565:25565 \
+          itzg/minecraft-server:latest
+          echo "Starting Purpur server..."
+          sleep 1
+      - name: Delayed server health check
+        run: |
+          echo "Waiting for server to become healthy..."
+          for i in {1..20}; do
+            healthy=$(docker exec test-purpur-server mc-monitor status --host 127.0.0.1 || echo "unhealthy")
+            echo "Status: $healthy"
+            if [[ "$healthy" == *"online"* ]]; then
+              echo "Server is online!"
+              exit 0
+            fi
+            sleep 6
+          done
+          echo "Server failed health check, timeout."
+          exit 1
+      - name: Retrieve server logs
+        run: docker logs test-purpur-server
+      - name: Stop and clean up
+        if: always()
+        run: docker rm -f test-purpur-server || true
